export const CustomTypography = {
  "subHeader-regular": {
    fontFamily: "Nexa",
    fontSize: "24px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 400,
  },
  "subHeader-bold": {
    fontFamily: "Nexa",
    fontSize: "24px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 700,
  },
  "p-lg-regular": {
    fontFamily: "Nexa",
    fontSize: "18px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 400,
  },
  "p-lg-bold": {
    fontFamily: "Nexa",
    fontSize: "18px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 700,
  },
  "p-xlg-bold": {
    fontFamily: "Nexa",
    fontSize: "18px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 1000,
  },
  "p-md-300": {
    fontFamily: "Nexa",
    fontSize: "16px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 300,
  },
  "p-md-regular": {
    fontFamily: "Nexa",
    fontSize: "16px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 400,
  },
  "p-md-bold": {
    fontFamily: "Nexa",
    fontSize: "16px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 700,
  },
  "p-sm-regular": {
    fontFamily: "Nexa",
    fontSize: "12px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 400,
  },
  "p-xs-regular": {
    fontFamily: "Nexa",
    fontSize: "12px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 300,
  },
  "p-xs-bold": {
    fontFamily: "Nexa",
    fontSize: "12px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 700,
  },
  "label-lg-bold": {
    fontFamily: "Nexa",
    fontSize: "18px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 700,
  },
  "label-md-bold": {
    fontFamily: "Nexa",
    fontSize: "14px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 700,
  },
  "label-md-regular": {
    fontFamily: "Nexa",
    fontSize: "14px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 400,
  },
  "label-sm-regular": {
    fontFamily: "Nexa",
    fontSize: "12px",
    lineHeight: "normal",
    fontKerning: "0%",
    fontWeight: 400,
  },
  "label-sm-bold": {
    fontFamily: "Nexa",
    fontSize: "12px",
    lineHeight: "normal",
    fontWeight: 700,
  },
};
