import type { Metadata } from "next";
import "./globals.css";
import "../styles/palette.css";
import ThemeRegistry from "@/theme/ThemeRegistry";
import ApiProvider from "@/redux/ApiProvider";
import ClientLayout from "@/modules/layout/client-layout";
import { Providers } from "@/redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <ApiProvider>
            <Providers>
              <ClientLayout>{children}</ClientLayout>
            </Providers>
          </ApiProvider>
        </body>
      </ThemeRegistry>
    </html>
  );
}
